HIPP-1251-Added Test credential tests
hmrc/api-hub-acceptance-tests pull request #50
Opened 2024-10-03 10:23 UTC by anu-nagula

2024-10-03 10:46 UTC, PaulCDurham requested changes

2024-10-03 10:46 UTC, PaulCDurham commented on src/test/scala/uk/gov/hmrc/test/ui/pages/application/EnvironmentAndCredentialsPage.scala
> +    val addCredentials: By = By.xpath("//button[normalize-space(text())='Add new credential']")
Could we please add an id element to the page? We're trying to avoid path selectors as they are fragile. You can ask a dev to do this.

2024-10-03 10:46 UTC, PaulCDurham commented on src/test/resources/features/Credentials.feature
> +    Then the client id should be added to the test environments credentials with count 1
I don't understand the wording here. When the application is registered it has a test environment credential. We're not creating anything. We haven't added to the test environments.

Scenario: A registered application has a test credential
When: the user selects the test environment tab
Then: the number of test credentials is 1

The "then" is using something more generic and re-usable.

2024-10-03 10:46 UTC, PaulCDurham commented on src/test/scala/uk/gov/hmrc/test/ui/pages/application/EnvironmentAndCredentialsPage.scala
> +  def selectAddCredentials(): Unit = {
The method name is a bit vague - test or production? Can we be more explicit?

Also methods should always return a PageObject never Unit. That helps us chain pages together in mini-journeys more easily. I'm guessing this method should return EnvironmentAndCredentialsPage?

2024-10-03 10:46 UTC, PaulCDurham commented on src/test/resources/features/Credentials.feature
> +    And the user chooses Add credentials
When not And. A scenario should have a triggering when. This probably needs to be "the user adds a test credential" or something like that to differentiate from adding a production credential.

2024-10-03 10:52 UTC, anu-nagula commented on src/test/scala/uk/gov/hmrc/test/ui/pages/application/EnvironmentAndCredentialsPage.scala
> +    val addCredentials: By = By.xpath("//button[normalize-space(text())='Add new credential']")
There is no id for this page object so used this.

2024-10-03 10:57 UTC, anu-nagula commented on src/test/resources/features/Credentials.feature
> +    Then the client id should be added to the test environments credentials with count 1
The wording was confusing for me too. This was "Create client id for registered application" an existing scenario I figured that its checking When an application is registered it has a test cred

2024-10-03 10:59 UTC, anu-nagula commented on src/test/scala/uk/gov/hmrc/test/ui/pages/application/EnvironmentAndCredentialsPage.scala
> +  def selectAddCredentials(): Unit = {
Agreed. How do you suggest to implement this if not return Unit? I'll change the method name to be more specific.

2024-10-03 10:59 UTC, anu-nagula commented on src/test/resources/features/Credentials.feature
> +    And the user chooses Add credentials
Agreed.

2024-10-03 13:41 UTC, anu-nagula commented on src/test/scala/uk/gov/hmrc/test/ui/pages/application/EnvironmentAndCredentialsPage.scala
> +    val addCredentials: By = By.xpath("//button[normalize-space(text())='Add new credential']")
Done

2024-10-07 08:31 UTC, PaulCDurham approved these changes

2024-10-07 08:32 UTC, merged